<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
      <OutputType>Library</OutputType>
      <TargetFramework>net10.0</TargetFramework>
      <ImplicitUsings>enable</ImplicitUsings>
      <Nullable>enable</Nullable>
      <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
      <IncludeSymbols>true</IncludeSymbols>
      <SymbolPackageFormat>snupkg</SymbolPackageFormat>
      <PackageId>nocscienceat.XPlaneWebConnector</PackageId>
      <Version>3.2.0</Version>
      <Authors>nocscienceat, Klemens Urban</Authors>
      <Description>A connector for the XPlane Web API</Description>
      <PackageLicenseExpression>MIT</PackageLicenseExpression>
      <Copyright>Copyright (c) nocscienceat</Copyright>
      <PackageReadmeFile>README.md</PackageReadmeFile>
      <RepositoryUrl>https://github.com/klemensurban/nocscienceat.XPlaneWebConnector</RepositoryUrl>
      <RepositoryType>git</RepositoryType>
    </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.3" />
  </ItemGroup>

</Project>
